### ISSUE TITLE
Fix patient identifiers

### ISSUE THREAD

**Issue by kevinzurek** [FEMR/femr#354]
The patient's ID is their primary key in the patients table, but this conflicts when you have two groups using separate deployments. (the first patient for each group would be 1 and the IDs should be unique).

The solution is to assign a number to each team and to each trip (this is now tracked), then append those numbers to the front of the current ID to get the new ID.

**Comment by delasteve** [comment]
Another way would be to use GUIDs.

**Comment by kevinzurek** [comment]
That was on the table for a while, but our concern was having to write down a GUID for every patient to have

**Comment by kevinzurek** [comment]
added to JIRA:

https://teamfemr.atlassian.net/browse/FEMR-29
